$ cat config.yaml
version: 5
daemon:
  log_level: info
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  '10DE:2203-BLAH:BLAH-0000:01:00.0':
    fan_control_enabled: true
    fan_control_settings:
      mode: curve
      static_speed: 0.5
      temperature_key: edge
      interval_ms: 500
      curve:
        40: 0.3019608
        50: 0.35
        60: 0.5
        70: 0.75
        80: 1.0
      spindown_delay_ms: 5000
      change_threshold: 2
    power_cap: 450.0
    min_core_clock: 210
    max_core_clock: 1950
    gpu_clock_offsets:
      0: 225
    mem_clock_offsets:
      0: 1500
current_profile: null
auto_switch_profiles: false